### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by 36000** [richford/cloudknot#198] opened 2019-12-03 07:52 UTC
When I run ck.Knot, I get:
```
BuildError: The command '/bin/sh -c pip install --no-cache-dir -r /tmp/requirements.txt     && pip install --no-cache-dir git+https://github.com/yeatmanlab/pyAFQ.git' returned a non-zero code: 1
```

Does this mean I have some conflicting imports?
The requirements file looks like this:
```
boto3==1.10.30
cloudpickle==1.2.2
dipy==1.0.0
nibabel==2.5.1
numpy==1.17.4
pandas==0.25.3
s3fs==0.4.0
```

When I try to install these, I get:
```
ERROR: awscli 1.16.271 has requirement botocore==1.13.7, but you'll have botocore 1.13.30 which is incompatible.
```

**Comment by richford** [comment] 2019-12-03 16:58
Thanks for filing the issue. Can you please post the code for the function that you pass to `ck.Knot()`?

**Comment by 36000** [comment] 2019-12-03 19:12
Here is the entire script, the third cell has the code:

https://github.com/36000/pyAFQ-scripts/blob/master/cloudknot/cloudknot_prek.ipynb

**Comment by ishanbhagawati** [comment] 2019-12-04 09:50
I am facing the same issue `error: botocore 1.13.32 is installed but botocore==1.12.45 is required by {'awscli'}`

uninstalling botocore and running again install command bypass this error but again complains on s3transfer package.

**Comment by richford** [comment] 2019-12-04 17:37
Thanks @ishanbhagawati and @36000 for letting us know. Honestly, I'm really stumped here. I'm unable to reproduce on my end. @36000, could we meet in person up at eScience sometime in the next few days or next week? I think I could be more helpful if I could look at the errors in person on your machine.

**Comment by ishanbhagawati** [comment] 2019-12-05 06:32
Hmm, I see @richford  let me know if you need any more information. Here are some more details:

Anaconda environment with python 3.7.1 
Operating System: macOS Mojave 10.14.6
Dependency details : [https://drive.google.com/file/d/1ltXFdgWOLNr0DNAwgcvFJHDkEfZ-gQ4h/view?usp=sharing](url)

Install command verbos log: [https://drive.google.com/file/d/1aFSdcAKJ-43fsC3E70LIxN9OW2aJNQrN/view?usp=sharing](url)

**Comment by richford** [comment] 2019-12-05 19:01
Thanks @ishanbhagawati! Are you at all affiliated with the University of Washington? If so, I could meet up with you in person on campus as well to try to diagnose the issue. If not, no big deal. I'll meet up with @36000. And I'm hopeful that fixing the issue for him will fix it for you as well.

**Comment by ishanbhagawati** [comment] 2019-12-06 04:52
@richford  No. I am from India actually. lets hope you and @36000  can meet fix the issue for him which in turn fixes my issue else otherwise will see what more can be done over the weekend

**Comment by richford** [comment] 2019-12-06 19:28
Hi @ishanbhagawati, I just met with @36000 and was able to resolve his error. #200 should close this issue. Unfortunately, I don't think it will fix your problem. So I've transferred your issue over to #201. Let's continue the conversation there.

**Closed** 2019-12-06 20:40 UTC
